-- Migration: Add summary to videos and create video_chapters table
-- Purpose: Support high-level summaries and semantic chapters from LLM analysis

-- 1. Add summary column to videos
ALTER TABLE public.videos ADD COLUMN IF NOT EXISTS summary TEXT;

COMMENT ON COLUMN public.videos.summary IS 'LLM-generated comprehensive summary of the video';

-- 2. Create video_chapters table
CREATE TABLE IF NOT EXISTS public.video_chapters (
    id bigserial PRIMARY KEY,
    video_id uuid NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
    title text NOT NULL,
    content text NOT NULL,
    start_time int NOT NULL DEFAULT 0,
    chapter_order int NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_video_chapters_video_id ON public.video_chapters(video_id);
CREATE INDEX IF NOT EXISTS idx_video_chapters_order ON public.video_chapters(video_id, chapter_order);

COMMENT ON TABLE public.video_chapters IS 'Semantic chapters/segments generated by LLM (non-time-synced)';
